// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kalougata/mall/api/v1/admin"
	"github.com/kalougata/mall/api/v1/mall"
	"github.com/kalougata/mall/pkg/app"
	"github.com/kalougata/mall/router/admin"
	"github.com/kalougata/mall/router/mall"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewApp(config *viper.Viper) (*app.Server, func(), error) {
	adminAPIRouter := adminv1.NewAdminAPIRouter()
	adminHTTPServer := adminrouter.NewAdminHTTPServer(adminAPIRouter)
	mallAPIRouter := mallv1.NewMallAPIRouter()
	mallHTTPServer := mallrouter.NewMallHTTPServer(mallAPIRouter)
	server := app.NewServer(adminHTTPServer, mallHTTPServer)
	return server, func() {
	}, nil
}
